/** @format */
// imports
import { useState } from "react";
import Head from "next/head";

// components
import Navbar from "../components/Navbar";
import List from "../components/List";

// styled
import {
  HomeWrap,
  ProductSearch,
  ProductSearchIcon,
  ProductSearchInput,
} from "../styles/HomeStyles";

export default function Home() {
  // states
  const [searchTerm, setSearchTerm] = useState("");
  return (
    <HomeWrap>
      <Head>
        <title>BookShop</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <ProductSearch htmlFor='search'>
        <ProductSearchInput
          type='text'
          name='search'
          id='search'
          placeholder='Search by title or author name...'
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
        />
        <ProductSearchIcon src='/images/search.svg' alt='search' />
      </ProductSearch>
      <List searchTerm={searchTerm} />
    </HomeWrap>
  );
}
